spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root

    password: yang136977

  jpa:
    hibernate:
      ddl-auto: update
    generation-ddl: true
    show-sql: true
#    database-platform: ch.qos.logback.core.db.dialect.MySQLDialect
server:
  port: 8081